CREATE Database DBDesignPJ;
/*  DROP Database PremierProducts */

USE DBDesignPJ;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Customer' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.Customer;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Booking' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.Booking;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PAYMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.PAYMENT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ROOM' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.ROOM;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ROOM_TYPE' AND TABLE_SCHEMA = 'dbo')

    DROP TABLE dbo.ROOM_TYPE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EMPLOYEE_ORDER' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.EMPLOYEE_ORDER;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CLEANING_ORDER' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.CLEANING_ORDER;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ROOM_REFILL' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.ROOM_REFILL;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EMPLOYEE' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.EMPLOYEE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PROCUREMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.PROCUREMENT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PROCUREMENT_TYPE' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.PROCUREMENT_TYPE;


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'BRANCH' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.BRANCH;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'BRANCH_DEPARTMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.BRANCH_DEPARTMENT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EMPLOYEE_ROLE' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.EMPLOYEE_ROLE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DEPARTMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.DEPARTMENT;


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FINANCIAL_PROCUREMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.FINANCIAL_PROCUREMENT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FINANCIAL_PAYMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.FINANCIAL_PAYMENT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FINANCIAL' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.FINANCIAL;


CREATE TABLE CUSTOMER (
    CUS_ID  int NOT NULL PRIMARY KEY,
	CUS_FNAME varchar(15),
	CUS_LNAME varchar(15),
	CUS_GENDER char(1),
	CUS_TEL  char(10),
	CUS_EMAIL varchar(50),
	CUS_FEEDBACK varchar(255),
	CUS_ADD_HOME_NUM varchar(50),
	CUS_ADD_STREET varchar(50),
	CUS_ADD_CITY varchar(50),
	CUS_ADD_STATE varchar(50),
	CUS_ADD_COUNTRY varchar(15),
	CUS_ADD_ZIPCODE varchar(50)
);	

-- CUS_ID  FOREIGN KEY REFERENCES PAYMENT(DeptID),
-- RM_NUM  FOREIGN KEY REFERENCES Department(DeptID),
CREATE TABLE BOOKING (
  BK_ID    int NOT NULL PRIMARY KEY,
  BK_DATE DATE ,
  BK_CHECK_IN_DATE DATE,
  BK_CHECK_OUT_DATE DATE,
  FOREIGN KEY (BK_CHECK_OUT_DATE)REFERENCES PAYMENT(DeptID)
 
);	

CREATE TABLE PAYMENT (
	PM_ID int NOT NULL PRIMARY KEY,
	BK_ID  int,
	PM_DATE DATE,
	PM_METHOD DATE,
	PM_COST DATE

);	

CREATE TABLE ROOM (
	RM_NUM int NOT NULL PRIMARY KEY,
	RT_ID  int,
	RM_OCCUPANCY varchar(20),
	RM_CLEAN_STATUS varchar(20),
	RM_TEL char(10)

);	

CREATE TABLE ROOM_TYPE (
	RT_ID  int NOT NULL PRIMARY KEY,
	RT_MAX_OCCUPANCY varchar(255),
	RT_BED_TYPE varchar(50),
	RT_BED_NUM int,
	RT_VIEW varchar(50),
	RT_LOUNGE varchar(50),
	RT_SUITE varchar(50),
	RT_PRICE_PER_NIGHT Money

);	


CREATE TABLE ROOM_REFILL (
	RR_ID int NOT NULL PRIMARY KEY,
	RM_NUM int,
	PRO_ID int,
	RR_QUANTITY int,
	RR_TIME DATETIME 
	
);	



CREATE TABLE EMPLOYEE (
	EMP_ID int NOT NULL PRIMARY KEY,
	BRC_ID int,
	ER_ID int,
	DEP_ID int,
	EMP_FNAME varchar(50),
	EMP_LNAME varchar(50),
	EMP_GENDER char(1),
	EMP_DOB Date,
	EMP_TEL char(10),
	EMP_SALARY Money,
	EMP_ADD_HOME_NUM  varchar(50),
	EMP_ADD_STREET  varchar(50),
	EMP_ADD_CITY varchar(50),
	EMP_ADD_STATE  varchar(50),
	EMP_ADD_COUNTRY  varchar(15),
	EMP_ADD_ZIPCODE  varchar(10)

);	

CREATE TABLE EMPLOYEE_ROLE (
	ER_ID int NOT NULL PRIMARY KEY,
	ER_NAME varchar(15),
	ER_DESCRIPTION varchar(255)


);	


CREATE TABLE EMPLOYEE_ORDER (
	EO_ID int NOT NULL PRIMARY KEY,
	EMP_ID int,
	CO_ID int ,
	EO_TIME DateTime,


);	


CREATE TABLE CLEANING_ORDER (
	CO_ID int NOT NULL PRIMARY KEY,
	RM_NUM int,
	CO_TIME DateTime


);	

CREATE TABLE PROCUREMENT (
	PRO_ID int NOT NULL PRIMARY KEY,
	PRT_ID int,
	BRC_ID int,
	PRO_QUANTITY int,
	PRO_PRICE Money,
	PRO_RESTOCK_TIME DateTime

);
	
CREATE TABLE PROCUREMENT_TYPE (
	PRT_ID int NOT NULL PRIMARY KEY,
	PRT_DESCRIPTION varchar(255)


);	

CREATE TABLE BRANCH (
	BRC_ID int NOT NULL PRIMARY KEY,
	BRC_NAME varchar(15),
	BRC_TEL varchar(10),
	BRC_EMAIL varchar(50),
	BRC_BRAND_NAME varchar(20),
	BRC_ADD_STREET varchar(50),
	BRC_ADD_CITY varchar(50),
	BRC_ADD_STATE varchar(50),
	BRC_ADD_COUNTRY varchar(15),
	BRC_ADD_ZIPCODE varchar(10)

);	


CREATE TABLE BRANCH_DEPARTMENT (
	BD_ID int NOT NULL PRIMARY KEY,
	BRC_ID int ,
	DEP_ID int

);	



CREATE TABLE DEPARTMENT (
	DEP_ID int NOT NULL PRIMARY KEY,
	DEP_NAME varchar(50),
	DEP_DESCRIPTION varchar(255)


);	

CREATE TABLE FINANCIAL (
	FIN_ID int NOT NULL PRIMARY KEY,
	FIN_AMOUNT int,
	FIN_DATETIME DateTime

);	

CREATE TABLE FINANCIAL_PROCUREMENT (
	FPR_ID int NOT NULL PRIMARY KEY,
	FIN_ID int,
	PRO_ID int,
	FPR_TIME DateTime

);	

CREATE TABLE FINANCIAL_PAYMENT (
	
	FP_ID int NOT NULL PRIMARY KEY,
	FIN_ID int,
	PM_ID int,	
	FPR_TIME DateTime

);	








