CREATE Database DBDesignPJ;
/*  DROP Database PremierProducts */

USE DBDesignPJ;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Customer' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.Customer;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Booking' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.Booking;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PAYMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.PAYMENT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ROOM' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.ROOM;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ROOM_TYPE' AND TABLE_SCHEMA = 'dbo')

    DROP TABLE dbo.ROOM_TYPE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EMPLOYEE_ORDER' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.EMPLOYEE_ORDER;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CLEANING_ORDER' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.CLEANING_ORDER;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ROOM_REFILL' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.ROOM_REFILL;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EMPLOYEE' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.EMPLOYEE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PROCUREMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.PROCUREMENT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PROCUREMENT_TYPE' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.PROCUREMENT_TYPE;


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'BRANCH' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.BRANCH;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'BRANCH_DEPARTMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.BRANCH_DEPARTMENT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EMPLOYEE_ROLE' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.EMPLOYEE_ROLE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DEPARTMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.DEPARTMENT;


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FINANCIAL_PROCUREMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.FINANCIAL_PROCUREMENT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FINANCIAL_PAYMENT' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.FINANCIAL_PAYMENT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FINANCIAL' AND TABLE_SCHEMA = 'dbo')
    DROP TABLE dbo.FINANCIAL;


CREATE TABLE CUSTOMER (
    CUS_ID  int NOT NULL PRIMARY KEY,
	CUS_FNAME varchar(15),
	CUS_LNAME varchar(15),
	CUS_GENDER char(1),
	CUS_TEL  char(10),
	CUS_EMAIL varchar(50),
	CUS_FEEDBACK varchar(255),
	CUS_ADD_HOME_NUM varchar(50),
	CUS_ADD_STREET varchar(50),
	CUS_ADD_CITY varchar(50),
	CUS_ADD_STATE varchar(50),
	CUS_ADD_COUNTRY varchar(15),
	CUS_ADD_ZIPCODE varchar(50)
);	


CREATE TABLE BOOKING (
  BK_ID    int NOT NULL PRIMARY KEY,
  CUS_ID  FOREIGN KEY REFERENCES PAYMENT(DeptID),
  RM_NUM  FOREIGN KEY REFERENCES Department(DeptID),
  BK_DATE 
  BK_CHECK_IN_DATE
  BK_CHECK_OUT_DATE
);	

CREATE TABLE PAYMENT (
	PM_ID 
	BK_ID,
	PM_DATE,
	PM_METHOD,
	PM_COST

);	

CREATE TABLE ROOM (
	RM_NUM
	RT_ID,
	RM_OCCUPANCY,
	RM_CLEAN_STATUS,
	RM_TEL

);	

CREATE TABLE ROOM_TYPE (
	RT_ID
	RT_MAX_OCCUPANCY,
	RT_BED_TYPE,
	RT_BED_NUM
	RT_VIEW,
	RT_LOUNGE,
	RT_SUITE,
	RT_PRICE_PER_NIGHT

);	


CREATE TABLE ROOM_REFILL (
	RR_ID,
	RM_NUM,
	PRO_ID,
	RR_QUANTITY,
	RR_TIME

);	



CREATE TABLE EMPLOYEE (
	EMP_ID,
	BRC_ID,
	ER_ID,
	DEP_ID
	EMP_FNAME,
	EMP_LNAME,
	EMP_GENDER,
	EMP_DOB,
	EMP_TEL,
	EMP_SALARY,
	EMP_ADD_HOME_NUM,
	EMP_ADD_STREET,
	EMP_ADD_CITY,
	EMP_ADD_STATE,
	EMP_ADD_COUNTRY,
	EMP_ADD_ZIPCODE

);	

CREATE TABLE EMPLOYEE_ROLE (
	ER_ID,
	ER_NAME,
	ER_DESCRIPTION


);	


CREATE TABLE EMPLOYEE_ORDER (
	EO_ID,
	EMP_ID,
	CO_ID,
	EO_TIME


);	


CREATE TABLE CLEANING_ORDER (
	CO_ID,
	RM_NUM,
	CO_TIME


);	

CREATE TABLE PROCUREMENT (
	PRO_ID
	PRT_ID,
	BRC_ID,
	PRO_QUANTITY,
	PRO_PRICE,
	PRO_RESTOCK_TIME

);
	
CREATE TABLE PROCUREMENT_TYPE (
	PRT_ID,
	PRT_DESCRIPTION


);	

CREATE TABLE BRANCH (
	BRC_ID,
	BRC_NAME,
	BRC_TEL,
	BRC_EMAIL,
	BRC_BRAND_NAME,
	BRC_ADD_STREET,
	BRC_ADD_CITY,
	BRC_ADD_STATE,
	BRC_ADD_COUNTRY,
	BRC_ADD_ZIPCODE

);	


CREATE TABLE BRANCH_DEPARTMENT (
	BD_ID,
	BRC_ID,
	DEP_ID

);	



CREATE TABLE DEPARTMENT (
	DEP_ID,
	DEP_NAME,
	DEP_DESCRIPTION


);	

CREATE TABLE FINANCIAL (
	FIN_ID,
	FIN_AMOUNT,
	FIN_DATETIME

);	

CREATE TABLE FINANCIAL_PROCUREMENT (
	FPR_ID,
	FIN_ID,
	PRO_ID,
	FPR_TIME

);	

CREATE TABLE FINANCIAL_PAYMENT (
	
	FP_ID,
	FIN_ID,
	PM_ID,	
	FPR_TIME

);	








